touch Biliary.txt
touch Bone.txt
touch Brain.txt
touch Breast.txt
touch Cervix.txt
touch Endometrium.txt
touch Eye.txt
touch Kidney.txt
touch LargeIntestine.txt		
touch Liver.txt	
touch Lung.txt	
touch Oesophagus.txt	
touch Ovary.txt	
touch Pancreas.txt	
touch Prostate.txt	
touch Skin.txt	
touch Stomach.txt	
touch Testis.txt	
touch Thyroid.txt	
touch Urinary.txt	